### ISSUE TITLE
Update _helpers.scss with new helpers

### ISSUE THREAD

**Issue by benbrehaut** [benbrehaut/halos#41]
````scss
// - - - - - - - - - - - - - - - - - - - - - - - - -
// :Helpers
// - - - - - - - - - - - - - - - - - - - - - - - - -

// Accessibility Hidden
// ------------------
._sr-hidden {
  @include element-invisible;
}

// Responsive Classes
// ------------------

// Show only function to generate hidden classes
@each $show-only in $breakpoint-classes {
  ._show-only--#{$show-only} {
    display: none;
  }
}

._show-only--sml {
  @include breakpoint(small only) {
    display: block;
  }
}

._show-only--med {
  @include breakpoint(medium only) {
    display: block;
  }
}

._show-only--lrg {
  @include breakpoint(large only) {
    display: block;
  }
}

// Background Colors
// ------------------
._slab-primary {
  background-color: $palette-primary;
}

._slab-secondary {
  background-color: $palette-secondary;
}

._slab-tertiary {
  background-color: $palette-tertiary;
}

// Text Colors
// ------------------
._text-color-primary {
  color: $palette-primary;
}

._text-color-secondary {
  color: $palette-secondary;
}

._text-color-tertiary {
  color: $palette-tertiary;
}

// Text Helpers
// ------------------
._text-caps {
  text-transform: uppercase;
}

._text-l {
  text-align: left;
}

._text-c {
  text-align: center;
}

._text-r {
  text-align: right;
}

````
